/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Games = 'gi' | 'hsr' | 'zzz';

export type Generated<T> =
    T extends ColumnType<infer S, infer I, infer U>
        ? ColumnType<S, I | undefined, U>
        : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Accounts {
    createdAt: Generated<Timestamp>;
    discordId: Int8;
    game: Games;
    id: Int8;
    modifiedAt: Generated<Timestamp>;
}

export interface Users {
    createdAt: Generated<Timestamp>;
    guildId: Int8;
    id: Int8;
    ltmidV2: string;
    ltokenV2: string;
    ltuidV2: string;
    modifiedAt: Generated<Timestamp>;
}

export interface DB {
    accounts: Accounts;
    users: Users;
}
